version: 0.2

env:
  variables:
    REGION: "us-west-2"
    AWS_ACCOUNTID: "588699980324"
    ECR_NAME: "mautic/development"
    EKS_NAME: "development-3"
    DEPLOYMENT_NAME: "mautic"
    REPOSITORY_URI: "${AWS_ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_NAME}"
  secrets-manager:
    DOCKER_USERNAME: "codebuild-env:DOCKER_USERNAME"
    DOCKER_PASSWORD: "codebuild-env:DOCKER_PASSWORD"

phases:
  install:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Logging to AWS ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com
      - echo Installing kubectl...
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Logging into docker
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo Update kubeconfig...
      - aws eks update-kubeconfig --name ${EKS_NAME} --region ${REGION} --role-arn arn:aws:iam::588699980324:role/DevelopmentEksCodeBuildkubectlRole

  build:
    commands:
      - echo Building Mautic Docker image...
      - docker build -t $REPOSITORY_URI:$COMMIT_HASH -f .build-config/Dockerfile .

  post_build:
    commands:
      - echo Pushing ECR...
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Rollout new version
      - kubectl set image -n saucey deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$REPOSITORY_URI:$COMMIT_HASH